### ISSUE TITLE
Window Boxing Fix

### ISSUE THREAD

**Issue by Soundtoxin** [hmxmilohax/rock-band-1-deluxe#3]
Does this mod fix the window boxing or plan to? On PS3 on a monitor without overscan there is a black border all the way around the picture. There is no menu entry in the default game to fix this, unlike newer games.

**Comment by lunalawl** [comment]
overscan in rb1 is enabled by going through manual calibration

**Comment by Soundtoxin** [comment]
Thanks! That was hidden pretty well.
