### ISSUE TITLE
Feature Request: Delete Song Option

### ISSUE THREAD

**Issue by Soundtoxin** [hmxmilohax/rock-band-1-deluxe#4]
On PS3 I had some bugged DLC songs (get a message that the data isn't there, sent back to main menu, which is a huge pain because of how long it takes to get back to where I was)  that I had to delete. I had to do so over FTP, and in one case I had to hand-edit a songs.dta file because I had other songs by the same artist that worked and it stayed in the list even after deleting the song files for the bad song due to it being in the songs.dta file. I believe in newer games you can delete songs from the song select. That would've been a lifesaver here and seems like a good feature to have.

**Comment by lunalawl** [comment]
very likely not possible

**Comment by Soundtoxin** [comment]
Darn, alright. Feel free to close then. At least now someone can search the issues if they were curious about the same thing.
