### ISSUE TITLE
Feature Request: Skip to bottom of list

### ISSUE THREAD

**Issue by Soundtoxin** [hmxmilohax/rock-band-1-deluxe#5]
If you're playing Solo Tour and you want to get to the DLC songs, they're way at the bottom, and if you've played all the built-in songs already there's a lot to scroll through. Having one of the frets let you jump to the bottom of the list in one shot would be awesome.

**Comment by lunalawl** [comment]
probably not possible

**Comment by Soundtoxin** [comment]
Darn, alright. Feel free to close then. At least now someone can search the issues if they were curious about the same thing.
