### ISSUE TITLE
Build PS3 not working

### ISSUE THREAD

**Issue by wintyre01** [hmxmilohax/rock-band-1-deluxe#8]
I'm trying to get this setup on RPCS3, but when I move the ark and hdr files to the game's gen folder, I'm met with a disc read error. I've seen a few videos of it working and I've followed all the instructions on the README (as well as used what I know from building RB2 and 3 Deluxe), so I don't know what I'm doing wrong.
<img width="962" alt="RB1DX" src="https://github.com/hmxmilohax/rock-band-1-deluxe/assets/143204241/e07d6c0c-7aa0-421e-89b7-9da6176b50fe">

**Comment by lunalawl** [comment]
Please re-dump your game and read the updated readme, apologies for the confusion
